name: Kenichi Bot

on:
  push:
    paths:
      - 'Records/kenichi.txt'
      - '.github/workflows/kenichi.yml'
  workflow_dispatch:

env:
  GitHubMail: "95846079+inferious-king@users.noreply.github.com"
  GitHubName: "inferious-king"
  fernet_key: ${{ secrets.FERNET_KEY }}

jobs:
  Kenichi_X:
    runs-on: ubuntu-20.04
    steps:
      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
      - uses: styfle/cancel-workflow-action@0.9.0
        name: "Cancel duplicate runs"
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      - name: Setup Py3
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9.12'
      - name: Gather repo
        run: |
          git clone "https://${{ secrets.GH_TOK }}@github.com/adarsh-goel/otp-bot" bot || exit 1
          git clone "https://${{ secrets.GH_TOK }}@github.com/adarsh-goel/otp-db" dbase_p || exit 1
          git clone "https://${{ secrets.GH_TOK }}@github.com/adarsh-goel/kenichi-bot-DB" dbase || exit 1
      - name: Install deps
        run: |
          cd bot
          pip3 install wheel
          pip3 install -r requirements.txt
      - name: Build wheels
        timeout-minutes: 330
        continue-on-error: true
        run: |
          cd bot
          for f in *.py; do python3 "$f"
      - name: Quality Control
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY} lupo
          cd lupo || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > Records/kenichi.txt
          git add .
          git commit -m "Building [$(date -u +%D-%T%P)]"
          git push -q "https://${{ secrets.GH_TOK }}@github.com/${GITHUB_REPOSITORY}" HEAD:main || exit 1
